disabled_rules:
  - multiple_closures_with_trailing_closure
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
included:
  - TestTaskUltiself
excluded:
  - Pods
line_length: 200
identifier_name:
  excluded:
    - id
trailing_whitespace:
  ignores_empty_lines: true
